# Generated by Django 5.2.9 on 2026-02-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='biz_address',
        ),
    ]
