# Generated by Django 5.2.9 on 2026-02-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0004_address_user_cartitems_product_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='weight',
            field=models.FloatField(),
        ),
    ]
