# Generated by Django 5.2.9 on 2026-02-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_category_category_img_subcategory_subcategory_img_and_more'),
        ('biz', '0005_alter_cartitems_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='adm.customerprofile'),
        ),
    ]
