# Generated by Django 5.2.9 on 2026-02-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_alter_cartitems_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='weight',
            field=models.FloatField(max_length=50),
        ),
    ]
