# Generated by Django 5.2.9 on 2026-02-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0006_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='sm1000001', max_length=20),
            preserve_default=False,
        ),
    ]
