# Generated by Django 5.2.9 on 2026-03-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_product_unit_alter_product_product_image'),
        ('biz', '0007_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='adm.customerprofile'),
        ),
    ]
