# Generated by Django 5.2.9 on 2026-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0008_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='category',
            field=models.CharField(default='home', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='9876543212', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
