# Generated by Django 6.0.2 on 2026-02-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_category_subcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
