# Generated by Django 6.0.2 on 2026-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_category_updated_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tamil_name',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_status',
            field=models.BooleanField(default=False),
        ),
    ]
