# Generated by Django 5.2.9 on 2026-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_otpverification_adminprofile_customerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
