# Generated by Django 6.0.2 on 2026-02-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
