# Generated by Django 6.0.2 on 2026-02-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_delete_category_delete_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
