# Generated by Django 5.2.9 on 2026-02-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
