# Generated by Django 5.2.9 on 2026-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_remove_user_address_remove_user_deact_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='product_snap'),
        ),
    ]
