# Generated by Django 6.0.2 on 2026-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_remove_product_trend_status_trendingproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='current_trending',
            field=models.BooleanField(default=False),
        ),
    ]
