# Generated by Django 6.0.2 on 2026-02-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_alter_trendingproduct_current_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingproduct',
            old_name='current_trending',
            new_name='current_trending_status',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1000, null=True),
        ),
    ]
