# Generated by Django 5.2.9 on 2026-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_category_category_img_subcategory_subcategory_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
