# Generated by Django 6.0.2 on 2026-02-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_rename_current_trending_trendingproduct_current_trending_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='current_trending_status',
            field=models.BooleanField(default=True),
        ),
    ]
