# Generated by Django 5.2.9 on 2026-02-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_otpverification_email_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
