# Generated by Django 6.0.2 on 2026-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_alter_trendingproduct_current_trending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
