# Generated by Django 5.2.9 on 2026-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
