# Generated by Django 5.2.9 on 2026-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_alter_otpverification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
