# Generated by Django 6.0.2 on 2026-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
