# Generated by Django 5.2.9 on 2026-02-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(null=True, upload_to='category_snap'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='product_snap'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_img',
            field=models.ImageField(null=True, upload_to='subcategory_snap'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
