# """
# Django settings for mithin_ecommerce_api project.

# Generated by 'django-admin startproject' using Django 5.1.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """
# import os
# from pathlib import Path
# from datetime import timedelta

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!

# # DEVELOPMENT
# # SECRET_KEY = 'django-insecure-@(3kwb+y6j)=w$g16$q6%@u@+@-ncdiq-00)ijn4&rd^8##@(p'

# #PRODUCTION 
# SECRET_KEY = 'django-insecure-@(3kwb+y6j)=w$g16$q6%@u@+@-ncdiq-00)ijn4&rd^8##@(p'
# # SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = False

# # DEVELOPMENT
# # ALLOWED_HOSTS = []
# # ALLOWED_HOSTS = [
# #     "127.0.0.1",
# #     "localhost",
# #     "ec2-54-237-228-110.compute-1.amazonaws.com",
# #     "smvegmart.com"
# # ]

# #PRODUCTION
# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

# CORS_ALLOW_ALL_ORIGINS = False

# #DEVELOPMENT
# # CORS_ALLOWED_ORIGINS = [
# #     "http://localhost:5173",
# #     # "ec2-54-237-228-110.compute-1.amazonaws.com:86",
# #     "http://localhost:4173",
# #     "https://smvegmart.com"
# # ]


# #PRODUCTION
# CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")

# CORS_ALLOW_CREDENTIALS = True


# #DEVELOPMENT
# # CSRF_TRUSTED_ORIGINS = [
# #     "https://smvegmart.com",
# #     "http://ec2-54-237-228-110.compute-1.amazonaws.com:86",
    
# # ]

# #PRODUCTION
# CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")


# # Authentication User model
# AUTH_USER_MODEL = 'adm.User'
# # Application definition

# INSTALLED_APPS = [
#     'daphne',
#     'adm',
#     'biz',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'utils',
#     'rest_framework_simplejwt',
#     'channels',
#     'corsheaders',
#     # 'django_huey',
#      'huey.contrib.djhuey',
#     'django.contrib.postgres',
#     "storages",

# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     "mithin_ecommerce_api.middleware.DisableCSRFMiddleware",
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]


# ROOT_URLCONF = 'mithin_ecommerce_api.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# ASGI_APPLICATION = 'mithin_ecommerce_api.asgi.application'

# WSGI_APPLICATION = 'mithin_ecommerce_api.wsgi.application'



# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# # localdevelopment
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql_psycopg2',
# #         'NAME': 'mithin_ecommerce_api',
# # 		'USER': 'postgres',
# #         'PASSWORD': 'M@dysakthi41',
# #         'HOST': 'localhost',
# #         'PORT': '5432',
# #     }
# # }

# # dev server
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql_psycopg2',
# #         'NAME': 'mithin_ecommerce_api',
# # 		'USER': 'mithin_ecommerce_user',
# #         'PASSWORD': 'm!th!n@ppu53r',
# #         'HOST': 'localhost',
# #         'PORT': '2930',
# #     }
# # }

# #DEVELOPMENT
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'mithin_ecommerce_api',
# #         'USER': 'madhavan',
# #         'PASSWORD': 'Madysakthi41',
# #         'HOST': 'aws-rds-db2.cwvkqm4aci4o.us-east-1.rds.amazonaws.com',
# #         'PORT': '5432',
# #         'OPTIONS': {
# #             'sslmode': 'require',
# #         },
# #     }
# # }

# #PRODUCTION
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("DB_NAME"),
#         "USER": os.environ.get("DB_USER"),
#         "PASSWORD": os.environ.get("DB_PASSWORD"),
#         "HOST": os.environ.get("DB_HOST"),
#         "PORT": os.environ.get("DB_PORT"),
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # Settings from here are newly added configs



# # Rest framework exception handler.
# REST_FRAMEWORK = {
#     'EXCEPTION_HANDLER': 'utils.exceptions.api_exception_handler',          #mithin_ecommerce_api.
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

# # SIMPLE JWT Configurations,
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': True,

#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUDIENCE': None,
#     'ISSUER': None,

#     'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'uid',

# }

# # Using the below configs directly for Access Token
# ACCESS_TOKEN_GENERIC_LIFETIME = timedelta(days=1)
# ACCESS_TOKEN_MOBILE_LIFETIME = timedelta(days=30)


# # Logger configuration
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "ERROR",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/gunicorn.error.log",
#         },
#     },
#     "root": {
#         "handlers": ["file"],
#         "level": "ERROR",
#     },
# }

# # For Testing purpose
# EMAIL_HOST ='smtp.gmail.com'
# EMAIL_HOST_USER ='sathish7639707@gmail.com'
# EMAIL_HOST_PASSWORD = "bcpqmsaxjjsnviri"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL = 'sathish7639707@gmail.com'



# # Production
# # EMAIL_HOST ='smtppro.zoho.in'
# # EMAIL_HOST_USER ='hello@finsmiles.com'
# # EMAIL_HOST_PASSWORD = "Fsm!l3sZ0h0"
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # DEFAULT_FROM_EMAIL = 'hello@finsmiles.com'



# #email
# #for testing
# #EMAIL_HOST ='smtp.gmail.com'
# #EMAIL_HOST_USER ='madhavanms0207@gmail.com'
# #EMAIL_HOST_PASSWORD = "aksjoxmisfxbxswz"
# #EMAIL_PORT = 587
# #EMAIL_USE_TLS = True
# #EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# #DEFAULT_FROM_EMAIL = 'madhavanms0207@gmail.com'

# # RQ_QUEUES = {
# #     'default': {
# #     'HOST': 'localhost',
# #     'PORT': 6379,
# #     'DB': 3,
# #     }
# #     # 'mail' :{
# #     # 'HOST': 'localhost',
# #     # 'PORT': 6379,
# #     # 'DB': 1,
# #     # }
# # }


# # django_crons
# # CRON_CLASSES = ['adm.cron.DailyTask',]
# # CRON_CLASSES = ['adm.cron.DailyLoop',]
# # CRON_CLASSES = ['adm.cron.DailySec',]
# # CRONJOBS = [    ('*/5 * * * *', 'adm.cron.do')]

# # huey
# HUEY = {
#     'name': 'mithin_ecommerce_api',  # Use db name for huey.
#     'result_store': True,  # Store return values of tasks.
#     'events': True,  # Consumer emits events allowing real-time monitoring.
#     'store_none': False,  # If a task returns None, do not save to results.
#     'immediate': False,  # If DEBUG=True, run synchronously.
#     'store_errors': True,  # Store error info if task throws exception.
#     'blocking': False,  # Poll the queue rather than do blocking pop.
#     'backend_class': 'huey.RedisHuey',  # Use path to redis huey by default,
#     'connection': {
#         'host': 'localhost',
#         'port': 6379,
#         'db': 1,
#         'connection_pool': None,  # Definitely you should use pooling!
#         # ... tons of other options, see redis-py for details.

#         # huey-specific connection parameters.
#         # 'read_timeout': 1,  # If not polling (blocking pop), use timeout.
#         # 'max_errors': 1000,  # Only store the 1000 most recent errors.
#         # 'url': None,  # Allow Redis config via a DSN.
#     },
#     'consumer': {
#         'workers': 1,
#         'worker_type': 'thread',
#         'initial_delay': 0.1,  # Smallest polling interval, same as -d.
#         'backoff': 1.15,  # Exponential backoff using this rate, -b.
#         'max_delay': 10.0,  # Max possible polling interval, -m.
#         'utc': False,  # Treat ETAs and schedules as UTC datetimes.
     
#         'timezone': 'Asia/Kolkata', # IST timezone
#         'scheduler_interval': 1,  # Check schedule every second, -s.
#         'periodic': True,  # Enable crontab feature.
#         'check_worker_health': True,  # Enable worker health checks.
#         'health_check_interval': 1,  # Check worker health every second.
#     },
#     # These two lines make Huey run crontab jobs in IST
#     'utc': False,
# }


# # this is for get youtube video duration while creating sections

# #DEVELOPMENT
# # YOUTUBE API_KEY
# API_KEY = "AIzaSyDwqJcZ0CgqIGGI7OyfHVXUBu1dmXP3jXg"

# #channels

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }

# # Static files (CSS, JavaScript, Images)
# STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # Media files (Pillow / User Uploads)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # DEVELOPMENT
# SITE_URL = "http://ec2-54-237-228-110.compute-1.amazonaws.com:88"

# # PRODUCTION
# SITE_URL = os.environ.get("SITE_URL")


# # DEVELOPMENT
# # For Google Maps.
# # GOOGLE_MAPS_API_KEY ="AIzaSyBi4EjhV-2YkjiOdlY42ZLBIvqBgipuQ08"

# # PRODUCTION
# # For Google Maps.
# GOOGLE_MAP_API_KEY = os.environ.get("GOOGLE_MAP_API_KEY")


# # AWS S2 CONFIG
# # PRODUCTION 
# AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")

# AWS_STORAGE_BUCKET_NAME = "mithin-ecommerce-images"
# AWS_S3_REGION_NAME = "us-east-1"

# AWS_DEFAULT_ACL = "public-read"
# AWS_QUERYSTRING_AUTH = False

# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/" 







# # #---------------------------------------
# # #-        NEW PORODUCTION SETUP        -
# # #---------------------------------------

# # import os
# # from pathlib import Path
# # from datetime import timedelta

# # BASE_DIR = Path(__file__).resolve().parent.parent

# # # ======================================================
# # # ENVIRONMENT
# # # ======================================================

# # ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")

# # DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# # # SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
# # SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-secret-key")


# # ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

# # # ======================================================
# # # CORS / CSRF
# # # ======================================================

# # CORS_ALLOW_ALL_ORIGINS = False
# # CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
# # CORS_ALLOW_CREDENTIALS = True

# # CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")


# # # ======================================================
# # # APPLICATIONS
# # # ======================================================

# # INSTALLED_APPS = [
# #     "daphne",
# #     "adm",
# #     "biz",
# #     "utils",
# #     "django.contrib.admin",
# #     "django.contrib.auth",
# #     "django.contrib.contenttypes",
# #     "django.contrib.sessions",
# #     "django.contrib.messages",
# #     "django.contrib.staticfiles",
# #     "django.contrib.postgres",
# #     "rest_framework",
# #     "rest_framework_simplejwt",
# #     "channels",
# #     "corsheaders",
# #     "huey.contrib.djhuey",
# #     "storages",
# # ]

# # # ======================================================
# # # MIDDLEWARE
# # # ======================================================

# # MIDDLEWARE = [
# #     "corsheaders.middleware.CorsMiddleware",
# #     "django.middleware.security.SecurityMiddleware",
# #     "django.contrib.sessions.middleware.SessionMiddleware",
# #     "django.middleware.common.CommonMiddleware",
# #     "mithin_ecommerce_api.middleware.DisableCSRFMiddleware",
# #     "django.middleware.csrf.CsrfViewMiddleware",
# #     "django.contrib.auth.middleware.AuthenticationMiddleware",
# #     "django.contrib.messages.middleware.MessageMiddleware",
# #     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# # ]

# # ROOT_URLCONF = "mithin_ecommerce_api.urls"

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # ASGI_APPLICATION = 'mithin_ecommerce_api.asgi.application'

# # WSGI_APPLICATION = 'mithin_ecommerce_api.wsgi.application'


# # # ======================================================
# # # DATABASE
# # # ======================================================

# # DATABASES = {
# #     "default": {
# #         "ENGINE": "django.db.backends.postgresql",
# #         "NAME": os.environ.get("DB_NAME"),
# #         "USER": os.environ.get("DB_USER"),
# #         "PASSWORD": os.environ.get("DB_PASSWORD"),
# #         "HOST": os.environ.get("DB_HOST"),
# #         "PORT": os.environ.get("DB_PORT"),
# #     }
# # }

# # # ======================================================
# # # AUTH USER
# # # ======================================================

# # AUTH_USER_MODEL = "adm.User"


# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
# #     },
# # ]


# # # Internationalization
# # # https://docs.djangoproject.com/en/5.1/topics/i18n/

# # LANGUAGE_CODE = 'en-us'

# # TIME_ZONE = 'UTC'

# # USE_I18N = True

# # USE_TZ = True


# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# # # ======================================================
# # # REST FRAMEWORK
# # # ======================================================

# # REST_FRAMEWORK = {
# #     "EXCEPTION_HANDLER": "utils.exceptions.api_exception_handler",
# #     "DEFAULT_PERMISSION_CLASSES": [
# #         "rest_framework.permissions.IsAuthenticated"
# #     ],
# #     "DEFAULT_AUTHENTICATION_CLASSES": [
# #         "rest_framework_simplejwt.authentication.JWTAuthentication"
# #     ],
# # }

# # # ======================================================
# # # JWT CONFIG
# # # ======================================================

# # # # SIMPLE JWT Configurations,
# # SIMPLE_JWT = {
# #     'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
# #     'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
# #     'ROTATE_REFRESH_TOKENS': False,
# #     'BLACKLIST_AFTER_ROTATION': True,

# #     'ALGORITHM': 'HS256',
# #     'SIGNING_KEY': SECRET_KEY,
# #     'VERIFYING_KEY': None,
# #     'AUDIENCE': None,
# #     'ISSUER': None,

# #     'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
# #     'USER_ID_FIELD': 'id',
# #     'USER_ID_CLAIM': 'uid',

# # }

# # # Using the below configs directly for Access Token
# # ACCESS_TOKEN_GENERIC_LIFETIME = timedelta(days=1)
# # ACCESS_TOKEN_MOBILE_LIFETIME = timedelta(days=30)

# # # ======================================================
# # # STATIC & MEDIA (DEVELOPMENT DEFAULT)
# # # ======================================================

# # # STATIC_URL = "/static/"
# # STATICFILES_DIRS = [BASE_DIR / "static"]
# # STATIC_ROOT = BASE_DIR / "staticfiles"

# # # MEDIA_URL = "/media/"
# # MEDIA_ROOT = BASE_DIR / "media"

# # # ======================================================
# # # CHANNELS / REDIS
# # # ======================================================

# # CHANNEL_LAYERS = {
# #     "default": {
# #         "BACKEND": "channels_redis.core.RedisChannelLayer",
# #         "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
# #     },
# # }

# # # ======================================================
# # # HUEY CONFIG
# # # ======================================================

# # # HUEY = {
# # #     "name": "mithin_ecommerce_api",
# # #     "backend_class": "huey.RedisHuey",
# # #     "connection": {
# # #         "host": "localhost",
# # #         "port": 6379,
# # #         "db": 1,
# # #     },
# # # }

# # # # huey
# # HUEY = {
# #     'name': 'mithin_ecommerce_api',  # Use db name for huey.
# #     'result_store': True,  # Store return values of tasks.
# #     'events': True,  # Consumer emits events allowing real-time monitoring.
# #     'store_none': False,  # If a task returns None, do not save to results.
# #     'immediate': False,  # If DEBUG=True, run synchronously.
# #     'store_errors': True,  # Store error info if task throws exception.
# #     'blocking': False,  # Poll the queue rather than do blocking pop.
# #     'backend_class': 'huey.RedisHuey',  # Use path to redis huey by default,
# #     'connection': {
# #         'host': 'localhost',
# #         'port': 6379,
# #         'db': 1,
# #         'connection_pool': None,  # Definitely you should use pooling!
# #         # ... tons of other options, see redis-py for details.

# #         # huey-specific connection parameters.
# #         # 'read_timeout': 1,  # If not polling (blocking pop), use timeout.
# #         # 'max_errors': 1000,  # Only store the 1000 most recent errors.
# #         # 'url': None,  # Allow Redis config via a DSN.
# #     },
# #     'consumer': {
# #         'workers': 1,
# #         'worker_type': 'thread',
# #         'initial_delay': 0.1,  # Smallest polling interval, same as -d.
# #         'backoff': 1.15,  # Exponential backoff using this rate, -b.
# #         'max_delay': 10.0,  # Max possible polling interval, -m.
# #         'utc': False,  # Treat ETAs and schedules as UTC datetimes.
     
# #         'timezone': 'Asia/Kolkata', # IST timezone
# #         'scheduler_interval': 1,  # Check schedule every second, -s.
# #         'periodic': True,  # Enable crontab feature.
# #         'check_worker_health': True,  # Enable worker health checks.
# #         'health_check_interval': 1,  # Check worker health every second.
# #     },
# #     # These two lines make Huey run crontab jobs in IST
# #     'utc': False,
# # }

# # # ======================================================
# # # EMAIL
# # # ======================================================

# # EMAIL_HOST = os.environ.get("EMAIL_HOST")
# # EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# # EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# # # ======================================================
# # # SITE CONFIG
# # # ======================================================

# # SITE_URL = os.environ.get("SITE_URL")

# # # ======================================================
# # # GOOGLE MAP
# # # ======================================================

# # GOOGLE_MAP_API_KEY = os.environ.get("GOOGLE_MAP_API_KEY")

# # # ======================================================
# # # LOGGING
# # # ======================================================

# # LOGGING = {
# #     "version": 1,
# #     "disable_existing_loggers": False,
# #     "handlers": {
# #         "file": {
# #             "level": "ERROR",
# #             "class": "logging.FileHandler",
# #             "filename": BASE_DIR / "logs/gunicorn.error.log",
# #         },
# #     },
# #     "root": {
# #         "handlers": ["file"],
# #         "level": "ERROR",
# #     },
# # }

# # # ======================================================
# # # S3 STORAGE (PRODUCTION ONLY)
# # # ======================================================

# # # if ENVIRONMENT == "production":

# # AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
# # AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")

# # AWS_STORAGE_BUCKET_NAME = "mithin-ecommerce-snaps"
# # AWS_S3_REGION_NAME = "us-east-1"
# # AWS_S3_ADDRESSING_STYLE = "virtual"
# # AWS_DEFAULT_ACL = None
# # AWS_QUERYSTRING_AUTH = False
# # AWS_S3_FILE_OVERWRITE = False
# # AWS_S3_SIGNATURE_VERSION = "s3v4"

# # STORAGES = {
# #     "default": {
# #         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
# #     },
# #     "staticfiles": {
# #         "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
# #     },
# # }

# # # DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
# # # STATICFILES_STORAGE = "storages.backends.s3boto3.S3StaticStorage"

# # STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/"
# # MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/"



"""
Django settings for mithin_ecommerce_api project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import multiprocessing
import os

if os.name == 'nt':
    
    multiprocessing.set_start_method('spawn',force=True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# React + Postman-la cookie work aaga idhu romba mukkiyam
SESSION_ENGINE = 'django.contrib.sessions.backends.db' # Database-la store panna
SESSION_COOKIE_HTTPONLY = True  # Security-kaaga (JS access panna mudiyaathu)
SESSION_SAVE_EVERY_REQUEST = True # Prathi request-layum session-ah update panna

# Cross-Domain (CORS) settings (React vera port-la irundha)
CORS_ALLOW_CREDENTIALS = True 
SESSION_COOKIE_SAMESITE = 'Lax' # Development-ku 'Lax' okay



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@(3kwb+y6j)=w$g16$q6%@u@+@-ncdiq-00)ijn4&rd^8##@(p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Authentication User model
AUTH_USER_MODEL = 'adm.User'
# Application definition

INSTALLED_APPS = [
    'daphne',
    'adm',
    'biz',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'utils',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',
    # 'django_huey',
     'huey.contrib.djhuey',
    'django.contrib.postgres',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
 
    "mithin_ecommerce_api.middleware.DisableCSRFMiddleware",

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'mithin_ecommerce_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'mithin_ecommerce_api.asgi.application'

WSGI_APPLICATION = 'mithin_ecommerce_api.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


#dev server
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mithin_ecommerce_api',
		'USER': 'mithin_ecommerce_user',
        'PASSWORD': 'm!th!n@ppu53r',
        'HOST': 'ec2-54-237-228-110.compute-1.amazonaws.com',
        'PORT': '2930',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Settings from here are newly added configs



# Rest framework exception handler.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'utils.exceptions.api_exception_handler',          #mithin_ecommerce_api.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# SIMPLE JWT Configurations,
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'uid',

}

# Using the below configs directly for Access Token
ACCESS_TOKEN_GENERIC_LIFETIME = timedelta(days=1)
ACCESS_TOKEN_MOBILE_LIFETIME = timedelta(days=30)


# Logger configuration
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "ERROR",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/gunicorn.error.log",
#         },
#     },
#     "root": {
#         "handlers": ["file"],
#         "level": "ERROR",
#     },
# }



# Production
# EMAIL_HOST ='smtppro.zoho.in'
# EMAIL_HOST_USER ='hello@finsmiles.com'
# EMAIL_HOST_PASSWORD = "Fsm!l3sZ0h0"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL = 'hello@finsmiles.com'



#email
#for testing
EMAIL_HOST ='smtp.gmail.com'
EMAIL_HOST_USER ='madhavanms0207@gmail.com'
EMAIL_HOST_PASSWORD = "aksjoxmisfxbxswz"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'madhavanms0207@gmail.com'

# RQ_QUEUES = {
#     'default': {
#     'HOST': 'localhost',
#     'PORT': 6379,
#     'DB': 3,
#     }
#     # 'mail' :{
#     # 'HOST': 'localhost',
#     # 'PORT': 6379,
#     # 'DB': 1,
#     # }
# }


# django_crons
# CRON_CLASSES = ['adm.cron.DailyTask',]
# CRON_CLASSES = ['adm.cron.DailyLoop',]
# CRON_CLASSES = ['adm.cron.DailySec',]
# CRONJOBS = [    ('*/5 * * * *', 'adm.cron.do')]

# huey
HUEY = {
    'name': 'mithin_ecommerce_api',  # Use db name for huey.
    'result_store': True,  # Store return values of tasks.
    'events': True,  # Consumer emits events allowing real-time monitoring.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': False,  # If DEBUG=True, run synchronously.
    'store_errors': True,  # Store error info if task throws exception.
    'blocking': False,  # Poll the queue rather than do blocking pop.
    'backend_class': 'huey.RedisHuey',  # Use path to redis huey by default,
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 1,
        'connection_pool': None,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.

        # huey-specific connection parameters.
        # 'read_timeout': 1,  # If not polling (blocking pop), use timeout.
        # 'max_errors': 1000,  # Only store the 1000 most recent errors.
        # 'url': None,  # Allow Redis config via a DSN.
    },
    'consumer': {
        'workers': 1,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1.15,  # Exponential backoff using this rate, -b.
        'max_delay': 10.0,  # Max possible polling interval, -m.
        'utc': False,  # Treat ETAs and schedules as UTC datetimes.
     
        'timezone': 'Asia/Kolkata', # IST timezone
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
    # These two lines make Huey run crontab jobs in IST
    'utc': False,
}


# this is for get youtube video duration while creating sections

# YOUTUBE API_KEY
API_KEY = "AIzaSyDwqJcZ0CgqIGGI7OyfHVXUBu1dmXP3jXg"

#channels

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# For Google Maps.
GOOGLE_MAPS_API_KEY ="AIzaSyBi4EjhV-2YkjiOdlY42ZLBIvqBgipuQ08"




SITE_URL = "http://ec2-54-237-228-110.compute-1.amazonaws.com:88"
