"""
Django settings for mithin_ecommerce_api project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import multiprocessing
import os

if os.name == 'nt':
    
    multiprocessing.set_start_method('spawn',force=True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@(3kwb+y6j)=w$g16$q6%@u@+@-ncdiq-00)ijn4&rd^8##@(p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Authentication User model
AUTH_USER_MODEL = 'adm.User'
# Application definition

INSTALLED_APPS = [
    'daphne',
    'adm',
    'biz',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'utils',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',
    # 'django_huey',
     'huey.contrib.djhuey',
    'django.contrib.postgres',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
 
    "mithin_ecommerce_api.middleware.DisableCSRFMiddleware",

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'mithin_ecommerce_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'mithin_ecommerce_api.asgi.application'

WSGI_APPLICATION = 'mithin_ecommerce_api.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# localdevelopment
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mithin_ecommerce_api',
		'USER': 'postgres',
        'PASSWORD': 'Bharath@2004',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


#dev server
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'mithin_ecommerce_api',
# 		'USER': 'mithin_ecommerce_user',
#         'PASSWORD': 'm!th!n@ppu53r',
#         'HOST': 'ec2-54-237-228-110.compute-1.amazonaws.com',
#         'PORT': '2930',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Settings from here are newly added configs



# Rest framework exception handler.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'utils.exceptions.api_exception_handler',          #mithin_ecommerce_api.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# SIMPLE JWT Configurations,
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'uid',

}

# Using the below configs directly for Access Token
ACCESS_TOKEN_GENERIC_LIFETIME = timedelta(days=1)
ACCESS_TOKEN_MOBILE_LIFETIME = timedelta(days=30)


# Logger configuration
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "ERROR",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/gunicorn.error.log",
#         },
#     },
#     "root": {
#         "handlers": ["file"],
#         "level": "ERROR",
#     },
# }



# Production
# EMAIL_HOST ='smtppro.zoho.in'
# EMAIL_HOST_USER ='hello@finsmiles.com'
# EMAIL_HOST_PASSWORD = "Fsm!l3sZ0h0"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# DEFAULT_FROM_EMAIL = 'hello@finsmiles.com'



#email
#for testing
EMAIL_HOST ='smtp.gmail.com'
EMAIL_HOST_USER ='madhavanms0207@gmail.com'
EMAIL_HOST_PASSWORD = "aksjoxmisfxbxswz"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'madhavanms0207@gmail.com'

# RQ_QUEUES = {
#     'default': {
#     'HOST': 'localhost',
#     'PORT': 6379,
#     'DB': 3,
#     }
#     # 'mail' :{
#     # 'HOST': 'localhost',
#     # 'PORT': 6379,
#     # 'DB': 1,
#     # }
# }


# django_crons
# CRON_CLASSES = ['adm.cron.DailyTask',]
# CRON_CLASSES = ['adm.cron.DailyLoop',]
# CRON_CLASSES = ['adm.cron.DailySec',]
# CRONJOBS = [    ('*/5 * * * *', 'adm.cron.do')]

# huey
HUEY = {
    'name': 'mithin_ecommerce_api',  # Use db name for huey.
    'result_store': True,  # Store return values of tasks.
    'events': True,  # Consumer emits events allowing real-time monitoring.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': False,  # If DEBUG=True, run synchronously.
    'store_errors': True,  # Store error info if task throws exception.
    'blocking': False,  # Poll the queue rather than do blocking pop.
    'backend_class': 'huey.RedisHuey',  # Use path to redis huey by default,
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 1,
        'connection_pool': None,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.

        # huey-specific connection parameters.
        # 'read_timeout': 1,  # If not polling (blocking pop), use timeout.
        # 'max_errors': 1000,  # Only store the 1000 most recent errors.
        # 'url': None,  # Allow Redis config via a DSN.
    },
    'consumer': {
        'workers': 1,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1.15,  # Exponential backoff using this rate, -b.
        'max_delay': 10.0,  # Max possible polling interval, -m.
        'utc': False,  # Treat ETAs and schedules as UTC datetimes.
     
        'timezone': 'Asia/Kolkata', # IST timezone
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
    # These two lines make Huey run crontab jobs in IST
    'utc': False,
}


# this is for get youtube video duration while creating sections

# YOUTUBE API_KEY
API_KEY = "AIzaSyDwqJcZ0CgqIGGI7OyfHVXUBu1dmXP3jXg"

#channels

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}





SITE_URL = "http://ec2-54-237-228-110.compute-1.amazonaws.com:88"